name: github_actions

on: workflow_dispatch

jobs:
  CI:
    permissions:
        contents: write # for actions/checkout to fetch code
        security-events: write # for codeql uploads
        actions: write
    runs-on: ubuntu-latest
    steps:
    - name: code-checkout
      uses: actions/checkout@v4
    
        
    - name: build&test
      env:
        JAVA_HOME: "jdk-17.0.10+7"
        MAVEN_HOME: "apache-maven-3.9.6"
      run: |
       wget https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.10%2B7/OpenJDK17U-jdk_x64_linux_hotspot_17.0.10_7.tar.gz
       tar xzvf OpenJDK17U-jdk_x64_linux_hotspot_17.0.10_7.tar.gz
       export JAVA_HOME=jdk-17.0.10+7
       wget https://dlcdn.apache.org/maven/maven-3/3.9.11/binaries/apache-maven-3.9.11-bin.tar.gz
       tar -xvf apache-maven-3.9.11-bin.tar.gz
       export MAVEN_HOME="apache-maven-3.9.11"
       export PATH="$MAVEN_HOME/bin:$PATH"
       export PATH="$JAVA_HOME/bin:$PATH"
       java --version
       mvn --version
       mvn clean spring-javaformat:apply
       mvn  package -Dcheckstyle.skip
       mvn jacoco:report

    - name: Archive coverage report
      run: |
        mkdir -p coverage-report
        cp target/**.jar coverage-report/
        cp target/jacoco.exec coverage-report/
        cp -r target/site/jacoco/* coverage-report/
        ls -lrt
        pwd
        ls -lrt
        cd coverage-report/
        ls -lrt
    
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: build-artifact
        path: |
           target/*.jar
           target/jacoco.exec
           target/site/jacoco/*

    - name: Upload unit test report
      uses: actions/upload-artifact@v4.6.2
      with:
        name: unit-test-report
        path: target/surefire-reports/*
          
    - name: Download CodeQL CLI
      run: |
          wget https://github.com/github/codeql-action/releases/latest/download/codeql-bundle-linux64.tar.gz
          tar -xzf codeql-bundle-linux64.tar.gz
          mv codeql-*/ codeql
          export PATH=$PWD/codeql:$PATH
          ./codeql --version

    - name: Create CodeQL database
      run: |
          ./codeql database create codeql-db \
            --language=java \
            --source-root=$PWD

    - name: Analyze with CodeQL
      run: |
          ./codeql database analyze codeql-db \
            --format=sarif-latest \
            --output=results.sarif
    - name: Upload CodeQL SARIF
      uses: github/codeql-action/upload-sarif@v3
      with:
          sarif_file: results.sarif
