name: github_actions

on: workflow_dispatch

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - name: code-checkout
      uses: actions/checkout@v4
      
    # - name: Set up JDK 17
    #   uses: actions/setup-java@v4
    #   with:
    #     java-version: '17'
        
    - name: build&test
      run: |
       apt-get update
       apt-get upgrade
       apt install openjdk-17-jdk -y
       mvn spring-javaformat:apply
       mvn clean install
      
