name: github_actions

on: workflow_dispatch

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - name: code-checkout
      uses: actions/checkout@v4
    
        
    - name: build&test
      run: |
       wget https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.10%2B7/OpenJDK17U-jdk_x64_linux_hotspot_17.0.10_7.tar.gz
       tar -xvf jdk-17_linux-x64_bin.tar.gz
       java --version
       mvn spring-javaformat:apply
       mvn clean install
      
