name: github_actions

on: workflow_dispatch

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - name: code-checkout
      uses: actions/checkout@v4
    
        
    - name: build&test
      env:
        JAVA_HOME: "jdk-17.0.10+7"
        MAVEN_HOME: "apache-maven-3.9.6"
      run: |
       wget https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.10%2B7/OpenJDK17U-jdk_x64_linux_hotspot_17.0.10_7.tar.gz
       tar xzvf OpenJDK17U-jdk_x64_linux_hotspot_17.0.10_7.tar.gz
       export JAVA_HOME=jdk-17.0.10+7
       wget https://dlcdn.apache.org/maven/maven-3/3.9.6/binaries/apache-maven-3.9.6-bin.tar.gz
       tar -xvf apache-maven-3.9.6-bin.tar.gz
       export MAVEN_HOME="apache-maven-3.9.6"
       export PATH="$MAVEN_HOME/bin:$PATH"
       export PATH="$JAVA_HOME/bin:$PATH"
       java --version
       mvn --version
       mvn clean spring-javaformat:apply
       mvn  package -Dcheckstyle.skip
       mvn jacoco:report
    
    # - name: publish code coverage
    #   run: echo "Code coverage report is available at ${{ github.workspace }}/coverage-report/index.html"
       

      
