name: github_actions

on: workflow_dispatch

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - name: code-checkout
      uses: actions/checkout@v4
    
        
    - name: build&test
      run: |
       wget https://download.oracle.com/java/17/latest/jdk-17_linux-x64_bin.tar.gz
       tar -xvf jdk-17_linux-x64_bin.tar.gz
       mvn spring-javaformat:apply
       mvn clean install
      
