name: github_actions

on: workflow_dispatch

jobs:
  CI:
    permissions:
        contents: write # for actions/checkout to fetch code
        security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
        actions: write
    runs-on: ubuntu-latest
    steps:
    - name: code-checkout
      uses: actions/checkout@v4
    
        
    - name: build&test
      env:
        JAVA_HOME: "jdk-17.0.10+7"
        MAVEN_HOME: "apache-maven-3.9.6"
      run: |
       wget https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.10%2B7/OpenJDK17U-jdk_x64_linux_hotspot_17.0.10_7.tar.gz
       tar xzvf OpenJDK17U-jdk_x64_linux_hotspot_17.0.10_7.tar.gz
       export JAVA_HOME=jdk-17.0.10+7
       wget https://dlcdn.apache.org/maven/maven-3/3.9.6/binaries/apache-maven-3.9.6-bin.tar.gz
       tar -xvf apache-maven-3.9.6-bin.tar.gz
       export MAVEN_HOME="apache-maven-3.9.6"
       export PATH="$MAVEN_HOME/bin:$PATH"
       export PATH="$JAVA_HOME/bin:$PATH"
       java --version
       mvn --version
       mvn clean spring-javaformat:apply
       mvn  package -Dcheckstyle.skip
       mvn jacoco:report

    - name: Archive coverage report
      run: |
        mkdir -p coverage-report
        cp target/**.jar coverage-report/
        cp target/jacoco.exec coverage-report/
        cp -r target/site/jacoco/* coverage-report/
        ls -lrt
        pwd
        ls -lrt
        cd coverage-report/
        ls -lrt
    
    - name: Zip coverage report
      run: zip -r coverage-report.zip coverage-report

    - name: Upload coverage report
      run: |
        set -x  # Enable debug mode
        echo "Uploading coverage report..."
        curl \
         -X POST \
         -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
         -H "Accept: application/vnd.github.v3+json" \
         -H "Content-Type: application/zip" \
         --data-binary "@./coverage-report.zip" \
         "https://github.com/RuthMariya/github-actions-cicd/actions"

      
